name: Update Sitemap

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches: [main]

jobs:
  update:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Update Sitemap
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install
      - run: node profiles.js
      - run: ./dupe.sh
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
